### ISSUE TITLE
If the target field is empty the "Duplicate error" always occurs

### ISSUE THREAD

**Issue by IskandarovRost** [adhawan325/cuba-duplicate-tools-addon#3]
1) Create a rule for some entity 
2) Select some base record field. Chose a not mandatory attribute.
3) Setup the postValidate method in the entity edit-screen as described in "readme"
4) Create an instance of the entity, leave the field empty

AR: Duplicate Records may not be created.
ER: It seems, when the property is empty there should be allowed to leave it empty.

**Comment by adhawan325** [comment]
@IskandarovRost - I agree - let me see what can be done about this.

**Comment by adhawan325** [comment]
I did some additional research into this and discovered that the code currently ignores null values (DuplicateRuleServiceBean:111).  The issue is described as follows:

Consider entity c1 with attributes a1 and a2.  Consider Rule r1 where base entity = c1, matching entity = c1, and 2 rule-detail records exists, exact match on a1, and exact match on a2.

Consider that the user creates record d1 where a1=test and a2=rule.  This passes because no other entity record of type c1 exists where a1 and a2 match these values.

Consider that user now creates record d2 where a1=test and a2 is blank.  Since we ignore nulls, we run the following check: a1=test, which passes, and we flag a duplicate.

I have updated the code so that the check will now be (a1=test && a2=null).  This should work for the above situation, however, now the issue is that for rules with a large number of non-mandatory fields that are configured as part of the rules, combinations of blank fields will work only once :)

I have also added a label to the UI describing this issue.

Thanks!
